- .github/workflows/codeql.yml
```
Code Security analysis
```
```
Addition Github codeql
```
> [CI] Create codeql.yml

- src/api/civo/main.go
- src/api/civo/main_test.go
- src/api/local/main.go
- src/api/local/main_test.go
- src/api/payload/main.go
Signed-off-by: Dipankar Das <dipankardas0115@gmail.com>
```
Adding support for windows environment
```
```
Used runtime.GOOS as the decider
```
> [API](Civo,Local) Added Windows File Path format

- README.md
- src/api/aks/main.go
- src/api/civo/main.go
- src/api/eks/main.go
- src/cli/cmd/init.go
Signed-off-by: Dipankar Das <dipankardas0115@gmail.com>
```
```
```
```
> [API](AWS,AZURE) Moved the Init credential to respective API handlers

- README.md
```
It was found that the link to the contribution guide is badly referenced
```
```
[ksctl](https://github.com/kubesimplify/ksctl)/CONTRIBUTING.md
```
> [Docs] Change of Contribution Guidelines

- api/aks/main.go
- api/eks/main.go
- api/local/main.go
- api/local/main_test.go
- api/utils/main.go
Closes https://github.com/kubesimplify/ksctl/issues/54
This PR introduces using a string Builder to minimise memory copy.
> [API] (ALL): use strings.Builder instead of repeated += for strings

- .github/workflows/go-fmt.yaml
- .github/workflows/testingAPI.yaml
- api/aks/main.go
- api/civo/main.go
- api/civo/main_test.go
- api/eks/main.go
- api/local/main_test.go
- api/test-api.ps1
- api/test-api.sh
- api/utils/main.go
- api/utils/main_test.go
- go.mod
- go.sum
- install.ps1
Signed-off-by: Dipankar Das <dipankardas0115@gmail.com>
Improve testing 
script to make it possible for all the provider to get `go test`
> Added script to run testing for all providers

- api/aksTesting.go
- api/azure/controlplane.go
- api/azure/database.go
- api/azure/ha_main.go
- api/azure/loadbalancer.go
- api/azure/main.go
- api/azure/managed_main.go
- api/azure/notes.md
- api/azure/utils.go
- api/azure/workernode.go
- api/civo/utils.go
- api/utils/main.go
- api/utils/main_test.go
- go.mod
- go.sum
- https://github.com/kubesimplify/ksctl/pull/67#issue-1577409536
> [API][HA](Azure) support for ha clusters

- .goreleaser.yaml
- update workflows for cosign 2.0
> update workflows for cosign 2.0

- .github/pull_request-template.md
- .github/workflows/automerge.yml
- api/azure/ha_main.go
- api/azure/main.go
- api/azure/main_test.go
- api/azure/managed_main.go
- api/azure/utils.go
- api/civo/ha_main.go
- api/civo/main.go
- api/civo/main_test.go
- api/civo/managed_main.go
- api/local/main.go
- api/logger/main.go
- api/logger/noteMsg.go
- api/utils/main.go
- cli/cmd/deleteClusterHAAzure.go
- cli/cmd/deleteClusterLocal.go
- cli/cmd/getCluster.go
- cli/cmd/switchCluster.go
Fixes the Provider credential fetch from the Environment variables and file.
improves the printing needed for the credentials to work good!
added the environment  variable check before accessing the file containing the cred
if specific env not set try to fetch them from file If not found then panic i.e. exit code 1
> fix(api): environment variable for providers credentials

- website/docs/getting-started/install.md
- website/docs/intro.md
- website/docs/providers/azure.md
- website/docs/providers/civo.md
fix Video is not rendering on website
Changing the path to "../../videos/ksctl-install.mp4"  will work.
I tried changing the source to ../../static/videos/ksctl-install.mp4 but it failed.
> fix: video not rendering in website 

- pkg/utils/errors/errors.go
```[tasklist]
``` 
```[tasklist]
```
> feat: Add the first new error consts

- cmd/cli/cmd/featureFlags.go
- internal/k8sdistros/universal/applications.go
- internal/k8sdistros/universal/kubernetesAPI.go
- pkg/controllers/manager.go
- pkg/utils/consts/consts.go
- website/blog/2023-10-04-auto-scaling.md
- website/blog/2023-10-09-install-applications.md
```[tasklist]
``` 
```[tasklist]
```
> feat: added argocd support

- cmd/cli/cmd/featureFlags.go
- internal/k8sdistros/universal/applications.go
- internal/k8sdistros/universal/kubernetesAPI.go
- pkg/controllers/manager.go
- pkg/utils/consts/consts.go
- website/blog/2023-10-04-auto-scaling.md
- website/blog/2023-10-09-install-applications.md
```[tasklist]
``` 
```[tasklist]
```
> feature: kubernetes support for pre installed applications `argocd`

- internal/k8sdistros/universal/applications.go
adds the argorollout to the apps list
```[tasklist]
``` 
```[tasklist]
```
> feat: added argo-rollout support

- internal/cloudproviders/civo/civo_test.go
- internal/cloudproviders/civo/main.go
- internal/cloudproviders/civo/managed_main.go
```[tasklist]
``` 
```[tasklist]
```
> bug-fix(civo): updated to new name for default pre-installed apps managed clusters

- cmd/cli/cmd/root.go
- internal/k8sdistros/k3s/controlplane.go
- internal/k8sdistros/k3s/datastore.go
- internal/k8sdistros/k3s/k3s_test.go
- internal/k8sdistros/k3s/k3scontroller.go
- internal/k8sdistros/k3s/loadbalancer.go
- internal/k8sdistros/k3s/workerplane.go
- internal/k8sdistros/kubeadm/kubeadmcontroller.go
- internal/k8sdistros/universal/applications.go
- internal/k8sdistros/universal/cilium.go
- pkg/controllers/kubernetes/kubernetes.go
- pkg/controllers/manager.go
- pkg/resources/types.go
- test/e2e/azure/Jenkinsfile
- test/e2e/civo/Jenkinsfile
- test/e2e/local/Jenkinsfile
```[tasklist]
``` 
```[tasklist]
```
> feat: added support for CNI plugin `cilium` for HA cluster

- pkg/utils/errors/errors.go
it is for merging the changes to the main branch
```[tasklist]
```
> enhancement: added non-exhaustive standard error messages

- go.mod
- internal/cloudproviders/azure/azurego.go
- internal/cloudproviders/azure/managed_main.go
- internal/cloudproviders/azure/ssh.go
- internal/cloudproviders/azure/vm.go
```[tasklist]
```
```[tasklist]
```
> refactor: removed the old package for azure-go-sdk

- internal/cloudproviders/azure/managed_main.go
```[tasklist]
``` 
```[tasklist]
```
> enhancement: added the NodeOSUPgrade Policy for azure managed cluster

- CONTRIBUTING.md
> Fix: Broken link of CONTRIBUTING.md

- pkg/utils/utils.go
- pkg/utils/utils_test.go
refer: https://gist.github.com/devinodaniel/8f9b8a4f31573f428f29ec0e884e6673
```[tasklist]
``` 
```[tasklist]
```
> enhancement: updated the ssh keygen with go pkg

- Makefile
- internal/cloudproviders/local/local_test.go
- internal/cloudproviders/local/localgo.go
- internal/cloudproviders/local/main.go
- internal/cloudproviders/local/managed_main.go
- pkg/controllers/cloud/cloud.go
- pkg/controllers/manager.go
- test/mock.go
- test/mock_test.go
```[tasklist]
``` 
```[tasklist]
```
> added mock to local provider

- pkg/helpers/ssh.go
- testing_targets/ssh_main.go
```[tasklist]
``` 
```[tasklist]
```
> added: test running for ssh

- README.md
```[tasklist]
``` 
```[tasklist]
```
> correct ksctl docs link

- internal/cloudproviders/azure/network.go
fix: Bug #283 
If the resources are already created then also call the createvirtnet and createsubnet.
> bug-fix: network creation process when its already created aka RESUME operation

- internal/k8sdistros/k3s/datastore.go
- pkg/helpers/state.go
Purpose: for it to be used by entire ksctl core
and can be helpful for setting hostnames for newly created VMs
- NONE
- #277
created to be used throughtout core and other parts
> moved the random string generator from `k3s` pkg to `helpers` pkg

- internal/cloudproviders/azure/azure_test.go
- internal/cloudproviders/azure/azurego.go
- internal/cloudproviders/azure/main.go
- internal/cloudproviders/azure/vm.go
- internal/cloudproviders/civo/civo_test.go
- internal/cloudproviders/civo/civogo.go
- internal/cloudproviders/civo/main.go
- internal/cloudproviders/civo/vm.go
- internal/k8sdistros/k3s/controlplane.go
- internal/k8sdistros/k3s/datastore.go
- internal/k8sdistros/k3s/helper.go
- internal/k8sdistros/k3s/k3s.go
- internal/k8sdistros/k3s/k3s_test.go
- internal/storage/types/k3s.go
- pkg/helpers/certs.go
- pkg/helpers/utils_test.go
- test/e2e/azure/create-ha.json
- test/e2e/civo/create-ha.json
- test/mock.go
> [!Note]
> Work on the ehancemnet proposal in this location 
> [Refer](https://github.com/ksctl/enhancements/tree/main/poc/etcd)
> [!Tip]
> etcd will be added for the k3s and future kubeadm support
TBD
- #247
> feat: add support for etcd for `k3s`

- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-civo.yml
- .github/workflows/e2e-local.yml
- .github/workflows/e2e.yml
- test/e2e/civo/create-ha.json
- test/e2e/civo/create.json
> feat: updated the core structure of the github workflow file

- internal/cloudproviders/civo/managed_main.go
- internal/cloudproviders/civo/network.go
there was no civo network status checking
- #9999
- #9999
> bug-fix: added missing network activation check

- internal/cloudproviders/aws/firewall.go
- internal/cloudproviders/aws/main.go
- internal/cloudproviders/aws/vm.go
- internal/cloudproviders/azure/azure_test.go
- internal/cloudproviders/azure/firewall.go
- internal/cloudproviders/azure/main.go
- internal/cloudproviders/azure/managed_main.go
- internal/cloudproviders/azure/vm.go
- internal/cloudproviders/civo/civo_test.go
- internal/cloudproviders/civo/firewall.go
- internal/cloudproviders/civo/main.go
- internal/cloudproviders/civo/managed_main.go
- internal/cloudproviders/civo/vm.go
- internal/cloudproviders/local/local_test.go
- internal/cloudproviders/local/main.go
- internal/cloudproviders/local/managed_main.go
- pkg/controllers/cloud/cloud.go
- pkg/controllers/manager.go
- pkg/logger/general_logging.go
- pkg/logger/logger_test.go
- pkg/logger/structured_logging.go
- pkg/types/controllers/cloud/cloud.go
- pkg/types/storage/aws.go
- pkg/types/storage/azure.go
- pkg/types/storage/civo.go
- pkg/types/storage/infrastructure.go
- pkg/types/storage/k8sBootstrap.go
- pkg/types/storage/local.go
> feature: add nodeSizes to the ksctl-state

- .github/workflows/ci-main.yaml
- .github/workflows/docker.yaml
- Makefile
- Makefile.components
- internal/kubernetes/helm.go
- pkg/controllers/manager.go
- pkg/helpers/fields.go
- pkg/logger/general_logging.go
- pkg/logger/structured_logging.go
- test/e2e/local/create.json
> bug-fix: failing helm client in macos

- .github/workflows/ci-tag.yml
- .github/workflows/codeql.yml
- .github/workflows/docker.yaml
- internal/kubernetes/ksctl.go
- ksctl-components/manifests/versions.go
- pkg/helpers/fields.go
- pkg/helpers/utils_test.go
- pkg/logger/general_logging.go
> Enhancement(ci): release of ksctl-components (versioning is left out)

- .github/workflows/codecov.yml
- .github/workflows/testingControllers.yml
- Makefile
- Makefile.components
- ksctl-components/agent/grpc_test.go
- ksctl-components/agent/ksctlagent_test.go
- ksctl-components/agent/pkg/application/app.go
- ksctl-components/agent/server.go
- ksctl-components/stateimport/main.go
- ksctl-components/stateimport/stateimport_test.go
- pkg/logger/general_logging.go
- scripts/test-api.ps1
- scripts/test-api.sh
- scripts/test-ksctl-agent.ps1
- scripts/test-ksctl-agent.sh
- scripts/test-ksctl-stateimport.ps1
- scripts/test-ksctl-stateimport.sh
> Feature: GRPC ksctl agent unit testing and also ksctl stateimport

- internal/cloudproviders/aws/awsgo.go
- internal/cloudproviders/azure/azurego.go
- internal/cloudproviders/civo/helper.go
- pkg/helpers/state.go
> feat: added UTC timezone for all the VM in their init script

- internal/k8sdistros/datastore.go
- internal/k8sdistros/k3s/controlplane.go
- internal/k8sdistros/k3s/workerplane.go
- internal/k8sdistros/kubeadm/controlplane.go
- internal/k8sdistros/kubeadm/kubeadm_test.go
- internal/k8sdistros/kubeadm/workerplane.go
- internal/k8sdistros/loadbalancer.go
- pkg/types/storage/kubeadm.go
- test/e2e/e2e.go
> feat(kubeadm): added auto renew of bootstrap token when near its expire

- internal/cloudproviders/aws/awsgo.go
- internal/cloudproviders/aws/vm.go
- internal/cloudproviders/azure/firewall.go
- internal/cloudproviders/azure/main.go
- internal/cloudproviders/azure/network.go
- internal/cloudproviders/azure/vm.go
- internal/cloudproviders/civo/main.go
- internal/cloudproviders/civo/managed_main.go
- internal/cloudproviders/civo/network.go
- internal/cloudproviders/civo/ssh.go
- internal/cloudproviders/civo/vm.go
- internal/cloudproviders/local/main.go
- internal/cloudproviders/local/managed_main.go
- internal/k8sdistros/k3s/controlplane.go
- internal/k8sdistros/k3s/helper.go
- internal/kubernetes/appsv1.go
- internal/kubernetes/corev1.go
- internal/kubernetes/flannel.go
- internal/kubernetes/ksctl.go
- internal/kubernetes/ksctl_controllers.go
- internal/kubernetes/kubeconfig_creds.go
- internal/storage/external/mongodb/mongodb.go
- pkg/controllers/managerClusterSelfManaged.go
- pkg/helpers/consts/consts.go
- pkg/helpers/retries.go
- pkg/helpers/ssh.go
- pkg/helpers/utils_test.go
- pkg/logger/general_logging.go
> enhancement: exponential backoff for every wait logic

- internal/cloudproviders/aws/aws_test.go
- internal/cloudproviders/aws/awsgo.go
- internal/cloudproviders/aws/network.go
- pkg/types/storage/aws.go
- https://github.com/ksctl/ksctl/issues/324
> Aws-ha test case

- .github/workflows/e2e.yml
- test/README.md
- test/gh-runner/configure/README.md
- test/gh-runner/configure/destroy.yml
- test/gh-runner/configure/gh-runner.yml
- test/gh-runner/configure/group_vars/all
- test/gh-runner/configure/setup-tools.yml
- test/gh-runner/configure/setup.yml
- test/gh-runner/configure/templates/path
- test/gh-runner/configure/templates/writeInventory.go
- test/gh-runner/configure/transfer.yml
- test/gh-runner/infra/.gitignore
- test/gh-runner/infra/README.md
- test/gh-runner/infra/aws_s3_policy.json
- test/gh-runner/infra/main.tf
- test/gh-runner/infra/vars.tf
> feat(e2e)!: automate creation and deletion of custom-runner infra

- .github/workflows/ci-main.yaml
- .github/workflows/ci-tag.yml
- .github/workflows/code-scanning.yml
- .github/workflows/docker.yaml
> feat(security)!: added docker image and IAC code scanning

- internal/kubernetes/applications.go
- internal/kubernetes/components/kwasm.go
- internal/kubernetes/components/kwasm_test.go
- internal/kubernetes/metadata/consts_test.go
- internal/kubernetes/metadata/vars.go
- internal/kubernetes/prod_apps.go
- internal/kubernetes/stacks/kwasm_wasmedge.go
- internal/kubernetes/stacks/stacks.go
> KFP: add kwasm wasmedge

- ksctl-components/agent/pkg/application/app.go
- ksctl-components/agent/server.go
- ksctl-components/manifests/controllers/application/deploy.yml
- ksctl-components/operators/application/api/v1alpha1/stack_types.go
- ksctl-components/operators/application/config/crd/bases/application.ksctl.com_stacks.yaml
- ksctl-components/operators/application/internal/controller/stack_controller.go
> Fixed the statuscode for application stack not working

- internal/cloudproviders/aws/main.go
- internal/cloudproviders/aws/vm.go
- internal/cloudproviders/azure/main.go
- internal/cloudproviders/azure/vm.go
- internal/cloudproviders/civo/main.go
- internal/cloudproviders/civo/vm.go
- internal/cloudproviders/local/main.go
- internal/k8sdistros/k3s/controlplane.go
- internal/k8sdistros/kubeadm/controlplane.go
- internal/k8sdistros/main.go
- internal/storage/external/mongodb/mongodb.go
- internal/storage/kubernetes/kubernetes.go
- internal/storage/local/local.go
> Removed the log debug on storageState

- .github/workflows/codecov.yml
> Updated the codecov

- internal/k8sdistros/k3s/controlplane.go
- internal/k8sdistros/k3s/k3s.go
- internal/k8sdistros/k3s/k3s_test.go
- internal/k8sdistros/kubeadm/controlplane.go
- internal/k8sdistros/kubeadm/kubeadm.go
- internal/k8sdistros/kubeadm/kubeadm_test.go
- pkg/controllers/bootstrap/bootstrap.go
- test/e2e/aws/scaledown-ha-kubeadm.json
- test/e2e/aws/scaledown-ha.json
- test/e2e/aws/scaleup-ha-kubeadm.json
- test/e2e/aws/scaleup-ha.json
- test/e2e/azure/scaledown-ha-kubeadm.json
- test/e2e/azure/scaledown-ha.json
- test/e2e/azure/scaleup-ha-kubeadm.json
- test/e2e/azure/scaleup-ha.json
- test/e2e/civo/scaledown-ha-kubeadm.json
- test/e2e/civo/scaledown-ha.json
- test/e2e/civo/scaleup-ha-kubeadm.json
- test/e2e/civo/scaleup-ha.json
> KEP(scale-up, scale-down): to use stateDocument for bootstrap provider and version

- internal/kubernetes/applications.go
- internal/kubernetes/components/argorollouts.go
- internal/kubernetes/components/argorollouts_test.go
- internal/kubernetes/components/certmanager.go
- internal/kubernetes/components/certmanager_test.go
- internal/kubernetes/components/cilium.go
- internal/kubernetes/components/cilium_test.go
- internal/kubernetes/components/components_test.go
- internal/kubernetes/components/flannel.go
- internal/kubernetes/components/flannel_test.go
- internal/kubernetes/components/istio.go
- internal/kubernetes/components/istio_test.go
- internal/kubernetes/components/kubeprometheus.go
- internal/kubernetes/components/kwasm.go
- internal/kubernetes/components/spinkube.go
- internal/kubernetes/components/spinkube_test.go
- internal/kubernetes/kubernetes_test.go
- internal/kubernetes/stacks/argorollouts.go
- internal/kubernetes/stacks/cilium.go
- internal/kubernetes/stacks/flannel.go
- internal/kubernetes/stacks/istio.go
- pkg/controllers/bootstrap/bootstrap.go
- pkg/controllers/managerClusterManaged.go
- pkg/controllers/managerClusterSelfManaged.go
- pkg/helpers/utilities/http_client.go
- pkg/helpers/utilities/http_client_test.go
Added the missing cilium and flannel latest release poll
- Fixes: #446
> Removed the app install on new cluster creation

- internal/kubernetes/components/kwasm.go
- internal/kubernetes/components/kwasm_test.go
- internal/kubernetes/metadata/consts_test.go
- internal/kubernetes/metadata/vars.go
- internal/kubernetes/prod_apps.go
- internal/kubernetes/stacks/kwasm_wasmedge.go
- internal/kubernetes/stacks/stacks.go
now added the wasmtime runtimeclass manifest to the URI manifest
- #9999
- #9999
> Patched: the wasmedge component to be generic

- .github/workflows/ci-tag.yml
> Updated the workflow

- pkg/provider/aws/meta/details.go
- pkg/provider/aws/meta/meta.go
- pkg/provider/aws/meta/pricing.go
- pkg/provider/azure/meta/details.go
- pkg/provider/provision_meta.go
- Fixes: #520 
---
<details>
<summary>💡 PR best practices</summary>
* Keep changes focused and atomic
* Update tests and documentation
* Check for conflicts with main branch
* Respond promptly to review comments
* Follow project coding standards
* Make sure you are using `pre-commit` for that run this command `$ pre-commit install`
</details>
> Addition of InstanceType Meta Label 

- pkg/provider/aws/meta/details.go
- pkg/provider/azure/meta/details.go
- pkg/provider/provision_meta.go
- Related to: ksctl/cli#61
---
<details>
<summary>💡 PR best practices</summary>
* Keep changes focused and atomic
* Update tests and documentation
* Check for conflicts with main branch
* Respond promptly to review comments
* Follow project coding standards
* Make sure you are using `pre-commit` for that run this command `$ pre-commit install`
</details>
> added changes in core for instance category

- pkg/handler/cluster/metadata/metadata.go
- pkg/provider/aws/meta/meta.go
- pkg/provider/aws/meta/pricing.go
- pkg/provider/azure/meta/meta.go
- pkg/provider/azure/meta/pricing.go
- pkg/provider/provision_meta.go
This pull request introduces functionality to fetch pricing information for instance types across different cloud providers (AWS and Azure). The changes include new methods to retrieve instance prices and modifications to existing methods to support the new functionality.
Key changes include:
* Added `GetPriceInstanceType` method in `AwsMeta` to fetch pricing information for a specific instance type in a given region.
* Introduced `priceVM` method in `pricing.go` to support fetching detailed pricing information for specific instance types.
* Updated `priceVMs` method to include additional filters for region-based pricing.
* Modified `priceSpecificEBS` and `priceSpeficEks` methods to include region-specific filters. [[1]](diffhunk://#diff-62882c92d60d2080ea25ccb9116f0802b17bf64feb1ba78edc79 …
> Working on Instance type recommendation wrt to region for cheap 💵 

- pkg/handler/cluster/metadata/metadata.go
- pkg/provider/optimizer/costs.go
- pkg/provider/optimizer/optimizer.go
- pkg/provider/optimizer/recommendation_test.go
- test/unit_test.go
This pull request includes several changes to the cost optimization logic across regions in the `pkg` directory. The most important changes include adding a new parameter to the `InstanceTypeOptimizerAcrossRegions` method, renaming methods to better reflect their functionality, and removing redundant sorting logic.
* [`pkg/handler/cluster/metadata/metadata.go`](diffhunk://#diff-b26385eb47dcb83b489888eb7404cb55c84878152c4c45895652c60a7f0a67c4R548): Added `regionMap` parameter to the `InstanceTypeOptimizerAcrossRegions` method in `CostOptimizeAcrossRegions` function. [[1]](diffhunk://#diff-b26385eb47dcb83b489888eb7404cb55c84878152c4c45895652c60a7f0a67c4R548) [[2]](diffhunk://#diff-b26385eb47dcb83b489888eb7404cb55c84878152c4c45895652c60a7f0a67c4R569)
* …
> 📈  Enhance Cost Optimization Across Regions with Emission Comparisons

- pkg/provider/optimizer/costs.go
- pkg/provider/optimizer/recommendation_test.go
…timizerAcrossRegions
- Fixes: #559
- Related to:
---
<details>
<summary>💡 PR best practices</summary>
* Keep changes focused and atomic
* Update tests and documentation
* Check for conflicts with main branch
* Respond promptly to review comments
* Follow project coding standards
* Make sure you are using `pre-commit` for that run this command `$ pre-commit install`
</details>
> bug-fix(optimizer): enhance emission sorting logic

- pkg/bootstrap/handler/cni/cilium.go
- pkg/bootstrap/handler/cni/cilium_test.go
- pkg/bootstrap/handler/cni/cni.go
- pkg/bootstrap/handler/k8s.go
- pkg/bootstrap/meta/meta.go
- pkg/handler/cluster/metadata/metadata.go
This pull request introduces enhancements to the CNI (Container Network Interface) handling in the project, focusing on guided configurations for Cilium, improved version management, and better logging. The key changes include the addition of guided configuration options for Cilium, new methods for fetching available Cilium and Flannel versions, and updates to the way CNIs are listed and managed.
* Added constants and a new `CiliumGuidedConfigurations` function to define guided setup options (e.g., Hubble, encryption, Prometheus, L7 proxy) for Cilium. (`pkg/bootstrap/handler/cni/cilium.go`, [pkg/bootstrap/handler/cni/cilium.goL26-R63](diffhunk://#diff-7654e2552ebe9e6cc82dbd286cc1d31bbaae724660be0c826d35724864ccf47aL26-R63))
* Updated `getCiliumComponentOverridings` and …
> ✨  Enhance Cilium Integration with Guided Configurations and Version Management for CNIs
